<?php

/**
 * Implements hook_module_implements_alter().
 *
 * @param $implementations
 * @param $hook
 */
function toolbar_update_notifications_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'page_top') {
    if (isset($implementations['update'])) {
      unset($implementations['update']);
    }
  }
}

/**
 * Implements hook_toolbar().
 */
function toolbar_update_notifications_toolbar() {
  $items = [];
  $items['update'] = [
    '#cache' => [
      'contexts' => [
        'user.permissions',
      ],
    ],
  ];

  $status = _toolbar_update_notifications_get_status();

  if (!$status['access']) {
    return $items;
  }

  $items['update'] += [
    '#type' => 'toolbar_item',
    'tab' => \Drupal\Core\Link::createFromRoute(t('Updates'), 'update.status')->toRenderable(),
    '#attached' => [
      'library' => [
        'toolbar_update_notifications/toolbar',
      ],
    ],
    '#wrapper_attributes' => [
      'class' => [
        'toolbar-tab-updates',
      ],
    ],
  ];

  $items['update']['tab']['#attributes']['class'][] = $status['type'];

  return $items;
}

function _toolbar_update_notifications_get_status() {
  /** @var \Drupal\Core\Routing\AdminContext $admin_context */
  $admin_context = \Drupal::service('router.admin_context');
  $route_match = \Drupal::routeMatch();

  $response = [
    'access' => TRUE,
    'type' => 'success',
  ];

  if (
    $admin_context->isAdminRoute($route_match->getRouteObject()) &&
    \Drupal::currentUser()->hasPermission('administer site configuration') &&
    \Drupal::currentUser()->hasPermission('view update notifications')
  ) {
    $route_name = \Drupal::routeMatch()->getRouteName();
    switch ($route_name) {
      // If we are on the appearance or modules list, display a detailed report
      // of the update status.
      case 'system.themes_page':
      case 'system.modules_list':
        $verbose = TRUE;
      break;

    }
    module_load_install('update');
    $status = update_requirements('runtime');
    foreach (['core', 'contrib'] as $report_type) {
      $type = 'update_' . $report_type;
      if (!empty($verbose)) {
        if (isset($status[$type]['severity'])) {
          if ($status[$type]['severity'] == REQUIREMENT_ERROR) {
            $response['type'] = 'error';
            return $response;
          }
          elseif ($status[$type]['severity'] == REQUIREMENT_WARNING) {
            $response['type'] = 'warning';
            return $response;
          }
        }
      }
      // Otherwise, if we're on *any* admin page and there's a security
      // update missing, print an error message about it.
      else {
        if (isset($status[$type])
          && isset($status[$type]['reason'])
          && $status[$type]['reason'] === UPDATE_NOT_SECURE) {
          $response['type'] = 'error';
          return $response;
        }
      }
    }
  }
  else {
    $response['access'] = FALSE;
  }
  return $response;
}